version: '2'
services:
    reservas-app:
        image: reservas
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://reservas-postgresql:5432/reservas
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - RABBITMQ_HOST=192.168.201.1
            - CONSENSO_MYHOSTNAME=1
        ports:
            - 8080:8080
    reservas-postgresql:
        extends:
            file: postgresql.yml
            service: reservas-postgresql
