version: '2'
services:
    reservas-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/reservas/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=reservas
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
